-- AC_MEMBER
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCACHE;

CREATE TABLE AC_MEMBER(
                          M_ID NUMBER(10) NOT NULL PRIMARY KEY,
                          M_EMAIL VARCHAR2(50) NOT NULL,
                          M_PWD VARCHAR2(50) NOT NULL,
                          M_NAME VARCHAR2(10) NOT NULL
);

-- AC_ACCOUNTBOOK
CREATE SEQUENCE ACCOUNTBOOK_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCACHE;

CREATE TABLE AC_ACCOUNTBOOK(
                               A_ID NUMBER(10) NOT NULL,
                               A_CODE NUMBER(6) NOT NULL,
                               M_ID NUMBER(10) NOT NULL,
                               PRIMARY KEY(A_ID, A_CODE),
                               FOREIGN KEY(M_ID) REFERENCES AC_MEMBER(M_ID) -- 회원이 등록한 가계부 월별 아이디를 구분하기 위한 고유 식별키를 지정한다.
);

INSERT INTO AC_ACCOUNTBOOK VALUES(ACCOUNTBOOK_SEQ.NEXTVAL, '202309', 1);

SELECT * FROM AC_ACCOUNTBOOK WHERE M_ID = '1' ORDER BY A_CODE;

-- AC_CATEGORY
CREATE TABLE AC_CATEGORY( -- 카테고리는 어느 회원이든 같은 카테고리명을 사용해야한다.
                            C_CODE VARCHAR2(10) NOT NULL PRIMARY KEY,
                            C_NAME VARCHAR2(20) NOT NULL
);

-- AC_DATE
CREATE TABLE AC_DATE(
                        D_DATE DATE NOT NULL PRIMARY KEY,
                        M_ID NUMBER(10) NOT NULL,
                        FOREIGN KEY(M_ID) REFERENCES AC_MEMBER(M_ID) -- 회원이 등록한 가계부 년월일자를 구분하기 위한 고유 식별키를 지정한다.
);

-- AC_MONTH
CREATE SEQUENCE MONTH_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 9999 NOCACHE;

CREATE TABLE AC_MONTH( -- JOIN TABLE로 가계부의 핵심 테이블이다.
                         M_ID NUMBER(10) NOT NULL PRIMARY KEY, -- SEQUENCE
                         ME_ID NUMBER(10) NOT NULL,
                         A_ID NUMBER(6) NOT NULL,
                         A_CODE NUMBER(6) NOT NULL,
                         C_CODE VARCHAR2(10) NOT NULL,
                         D_DATE DATE NOT NULL,
                         M_AMOUNT NUMBER(20) NOT NULL,
                         M_MEMO VARCHAR2(50), -- 메모는 생략 가능하다.
                         M_CREATE_DATE DATE, -- SYSTEM LOG
                         M_UPDATE_DATE DATE, -- SYSTEM LOG
                         FOREIGN KEY(ME_ID) REFERENCES AC_MEMBER(M_ID),
                         FOREIGN KEY(A_ID, A_CODE) REFERENCES AC_ACCOUNTBOOK(A_ID, A_CODE), -- 회원이 등록한 월별 가계부의 아이디를 구분하기 위한 고유 식별키를 지정한다.
                         FOREIGN KEY(C_CODE) REFERENCES AC_CATEGORY(C_CODE), -- 가계부 카테고리 목록을 불러오기 위한 고유 식별키를 지정한다.
                         FOREIGN KEY(D_DATE) REFERENCES AC_DATE(D_DATE) -- 회원이 등록한 월별 가계부의 년월일자를 불러오기 위한 고유 식별키를 지정한다.
);

INSERT INTO AC_MONTH(M_ID, ME_ID, A_ID, A_CODE, C_CODE, D_DATE, M_AMOUNT, M_MEMO, M_CREATE_DATE) VALUES (MONTH_SEQ.NEXTVAL, 1, 1, 202308, 'A01', TO_DATE('20230830','YY/MM/DD'), '10000000', '내 한달 월급이였으면 좋겠다.', SYSDATE);

SELECT MO.M_ID 월별_가계부_SEQ, MO.ME_ID 회원_아이디, A.A_ID 가계부_SEQ, A.A_CODE 가계부_년월_식별코드, MO.D_DATE 년월일자, C.C_CODE 가계부_카테고리_일련번호, C.C_NAME 가계부_카테고리명, MO.M_AMOUNT 금액, MO.M_MEMO 메모, MO.M_CREATE_DATE 등록일자
FROM AC_MEMBER M, AC_ACCOUNTBOOK A, AC_CATEGORY C, AC_DATE D, AC_MONTH MO
WHERE MO.ME_ID = A.A_ID AND C.C_CODE = MO.C_CODE AND D.D_DATE = MO.D_DATE AND MO.ME_ID = 1 AND A.A_CODE = 202308
GROUP BY MO.M_ID, MO.ME_ID, A.A_ID, A.A_CODE,MO.D_DATE, C.C_CODE, C.C_NAME, MO.M_AMOUNT, MO.M_MEMO, MO.M_CREATE_DATE;

-- DATE MERGE
MERGE INTO AC_DATE
USING DUAL ON (D_DATE = '20230825')
WHEN NOT MATCHED THEN INSERT(D_DATE, M_ID) VALUES(TO_DATE('20230825', 'YY/MM/DD'), 1);

-- MONTH CATEGORY
-- 1. 수입
SELECT C.C_NAME 카테고리명, SUM(M.M_AMOUNT) 가격, COUNT(C.C_NAME) 등록_횟수
FROM AC_CATEGORY C, AC_MONTH M
WHERE C.C_CODE = M.C_CODE AND C.C_CODE LIKE 'A%'
GROUP BY ROLLUP(C.C_NAME);

-- 2. 고정지출
SELECT C.C_NAME 카테고리명, SUM(M.M_AMOUNT) 가격, COUNT(C.C_NAME) 등록_횟수
FROM AC_CATEGORY C, AC_MONTH M
WHERE C.C_CODE = M.C_CODE AND C.C_CODE LIKE 'B%'
GROUP BY ROLLUP(C.C_NAME);

-- 3. 비고정지출
SELECT C.C_NAME 카테고리명, SUM(M.M_AMOUNT) 가격, COUNT(C.C_NAME) 등록_횟수
FROM AC_CATEGORY C, AC_MONTH M
WHERE C.C_CODE = M.C_CODE AND C.C_CODE LIKE 'C%'
GROUP BY ROLLUP(C.C_NAME);

-- JOIN QUERY
SELECT D_DATE, C.C_NAME, M_AMOUNT, M_MEMO
FROM AC_CATEGORY C, AC_MONTH M
WHERE C.C_CODE = M.C_CODE
GROUP BY D_DATE, C.C_NAME, M_AMOUNT, M_MEMO;

SELECT M.M_ID, M.A_ID, M.D_DATE, C.C_CODE, C.C_NAME, M_AMOUNT, M_MEMO
FROM AC_CATEGORY C, AC_MONTH M, AC_MEMBER ME, AC_ACCOUNTBOOK A
WHERE C.C_CODE = M.C_CODE AND A.M_ID = ME.M_ID AND A.M_ID = 1 AND A.A_ID = 202308
GROUP BY M.M_ID, M.A_ID, M.D_DATE, C.C_CODE, C.C_NAME, M_AMOUNT, M_MEMO
ORDER BY M.D_DATE;