-- [수입]
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'A' || INCOME_SEQ.NEXTVAL, '기본급', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'A' || INCOME_SEQ.NEXTVAL, '상여금', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'A' || INCOME_SEQ.NEXTVAL, '손익금', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'A' || INCOME_SEQ.NEXTVAL, '은행이자', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');

-- [저축] 사용자마다 다르므로 생략한다.
--INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'B' || SAVE_SEQ.NEXTVAL, '카카오뱅크 저금통', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');

-- [고정지출]
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'C' || FIX_SEQ.NEXTVAL, '월세', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'C' || FIX_SEQ.NEXTVAL, '관리비', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'C' || FIX_SEQ.NEXTVAL, '대출이자', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'C' || FIX_SEQ.NEXTVAL, '보험료', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'C' || FIX_SEQ.NEXTVAL, '휴대폰', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'C' || FIX_SEQ.NEXTVAL, '인터넷', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'C' || FIX_SEQ.NEXTVAL, '전기요금', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'C' || FIX_SEQ.NEXTVAL, '가스요금', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');

-- [비고정지출]
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '식사', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '배달', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '간식', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '식재료', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '편의점', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '생필품', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '가구가전', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '세탁업체', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '대중교통', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '택시', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '생활복', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '운동복', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '속옷', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '가방', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '신발', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '악세사리', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '화장품', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '미용실', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '문구', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '교육', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '문화', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '병원', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '약국', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '건강용품', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '건강식품', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '여행', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '선물', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '경조사', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '부모님', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '심부름', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');
INSERT INTO AC_CATEGORY(C_ID, M_ID, C_CODE, C_NAME, C_CREATE_DATE, C_ROLE) VALUES(CATEGORY_SEQ.NEXTVAL, 1, 'D' || NONFIX_SEQ.NEXTVAL, '기타', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'N');